pull_request_rules:
- name: automatic merge on CI success and review
  conditions:
  - status-success=continuous-integration/jenkins/pr-merge
  - status-success=Codacy/PR Quality Review
  actions:
    merge:
      method: merge