apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: portfolio
  name: portfolio
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 31496
  selector:
    io.kompose.service: portfolio
  type: NodePort
status:
  loadBalancer: {}
