apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: portfolio
  name: portfolio
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: portfolio
    spec:
      containers:
      - args:
        - --spring.cloud.config.uri=http://config.ketrwu.host:32044
        image: docker.ketrwu.host/portfolio
        name: portfolio
        resources: {}
        ports:
        - containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
