service: tempo-proxy
provider:
  name: aws
  runtime: java8
  region: eu-central-1
  memorySize: 256
  timeout: 20
  versionFunctions: false
  stage: ${self:custom.Stage}
  environment:
    STAGE: ${self:custom.Stage}

custom:
  Stage: ${env:STAGE, 'dev'}

package:
  artifact: server/target/server-2.0.0.war
